# Generated by Django 4.2.11 on 2026-03-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'permissions': [('view_manager_dashboard', 'Può vedere la dashboard manager')]},
        ),
    ]
